/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz_gráfica;

import POJO.Empleado;
import gestionConsultas.EmpleadoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edulumulu
 */
public class Eliminar_Empleado extends javax.swing.JDialog {

    private int id_selecionado;
    private ArrayList<Empleado> lista_empleados = new ArrayList<>();
    private EmpleadoDAO empleadoDAO = new EmpleadoDAO();

    /**
     * Creates new form Eliminar_Empleado
     */
    public Eliminar_Empleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //Deshabilito el boton de aceptar y cargo lista de empleados
        bt_aceptar.setEnabled(false);
        lista_empleados = empleadoDAO.listarEmpleados();

        //Añado al combo box los objetos empleado de la lista
        if (!lista_empleados.isEmpty()) {
            for (Empleado em : lista_empleados) {
                cb_empleados.addItem(em); // Guardar objetos en lugar de nombres
            }
        }

        //Listener para cuando se toca un elemento del combobox, cambia el boton aceptar a habilitado si hay un elemento selecionado
        cb_empleados.addActionListener(e -> bt_aceptar.setEnabled(cb_empleados.getSelectedItem() != null));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cb_empleados = new javax.swing.JComboBox<>();
        bt_aceptar = new javax.swing.JButton();
        bt_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Selecciona un empleado:");

        bt_aceptar.setText("Aceptar");
        bt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aceptarActionPerformed(evt);
            }
        });

        bt_Salir.setText("Salir");
        bt_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_Salir)
                        .addGap(18, 18, 18)
                        .addComponent(bt_aceptar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_aceptar)
                    .addComponent(bt_Salir))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Comprueba que el combo box esté selecionado y elimina o avisa por que no puede eliminar al empleado
     * @param evt 
     */
    private void bt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aceptarActionPerformed
        Empleado empleadoSeleccionado = (Empleado) cb_empleados.getSelectedItem();

        if (empleadoSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Seleccione un empleado antes de continuar", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Si el empleado existe y tiene incidencias lo elimina, si existe pero no tiene incidencias avisa de que no tiene incidencias, si no existe avisa
        if (empleadoDAO.eliminar_Empleado(empleadoSeleccionado) == 0) {
            JOptionPane.showMessageDialog(this, "Empleado --> " + empleadoSeleccionado.getNombre_completo() + " borrado con éxito", "Acción completada", JOptionPane.WARNING_MESSAGE);
            dispose();
        } else {
            if (empleadoDAO.eliminar_Empleado(empleadoSeleccionado) == 1) {
                JOptionPane.showMessageDialog(this, "No se ha podido borrar el empleado, tiene incidencias asociadas", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No existe el empleado en la base de datos", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            }
        }


    }//GEN-LAST:event_bt_aceptarActionPerformed

    private void bt_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_SalirActionPerformed
        dispose();
    }//GEN-LAST:event_bt_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar_Empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Eliminar_Empleado dialog = new Eliminar_Empleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Salir;
    private javax.swing.JButton bt_aceptar;
    private javax.swing.JComboBox<Empleado> cb_empleados;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
