
package interfaz_gráfica;

import POJO.Empleado;


/**
 * Menú principal con botones para abrir las diferentes ventanas
 * @author edulumulu
 */
public class Menu_incidencias extends javax.swing.JFrame {
    
    private Empleado empleado; 

    /**
     * Creates new form MainGráfico
     */
    public Menu_incidencias() {
        initComponents();
    }

    // Método para recibir el empleado de dialogo anterior
    public void setEmpleado(Empleado empleado) {
        if (empleado == null) {
        throw new IllegalArgumentException("El empleado recibido es null");
    }
        this.empleado = empleado;
    }

    // Método para acceder al empleado de dialogo anterior
    public Empleado getEmpleado() {
        return this.empleado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_ingresar = new javax.swing.JButton();
        jButton2Salir = new javax.swing.JButton();
        bt_listar = new javax.swing.JButton();
        bt_incidenciaporid = new javax.swing.JButton();
        bt_incidencia_por_empelado = new javax.swing.JButton();
        bt_incidencias_para_empleado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú incidencias");
        setBackground(new java.awt.Color(51, 255, 51));
        setResizable(false);

        bt_ingresar.setText("Ingresar incidencia");
        bt_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ingresarActionPerformed(evt);
            }
        });

        jButton2Salir.setText("Salir");
        jButton2Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2SalirActionPerformed(evt);
            }
        });

        bt_listar.setText("Listado de incidencias");
        bt_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_listarActionPerformed(evt);
            }
        });

        bt_incidenciaporid.setText("Incidencia a partir de id");
        bt_incidenciaporid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incidenciaporidActionPerformed(evt);
            }
        });

        bt_incidencia_por_empelado.setText("Incidencias por empleado");
        bt_incidencia_por_empelado.setToolTipText("");
        bt_incidencia_por_empelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incidencia_por_empeladoActionPerformed(evt);
            }
        });

        bt_incidencias_para_empleado.setText("Incidencias destinadas a un empleado");
        bt_incidencias_para_empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_incidencias_para_empleadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bt_incidencia_por_empelado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_incidenciaporid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_listar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(bt_ingresar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_incidencias_para_empleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2Salir)
                .addGap(148, 148, 148))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(bt_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_incidenciaporid, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_incidencia_por_empelado, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bt_incidencias_para_empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jButton2Salir)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2SalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2SalirActionPerformed

    /**
     * Abro el dialogo siguiente y envío un empleado
     * @param evt 
     */
    private void bt_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ingresarActionPerformed
       
        Insertar_inicidencia l = new Insertar_inicidencia(this, true);
        // Verifica que empleado no sea null antes de pasarlo
    if (empleado != null) {
        l.setEmpleado(empleado);
        System.out.println("Empleado pasado correctamente: " + empleado.getNombre_usuario());
    } else {
        System.out.println("Empleado es null en Menu_incidencias");
    }
        l.setLocationRelativeTo(null);
        l.setVisible(true);

    }//GEN-LAST:event_bt_ingresarActionPerformed

    private void bt_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_listarActionPerformed
        Mostrar_incidencias l = new Mostrar_incidencias(this, true);
        l.setLocationRelativeTo(null);
        l.setVisible(true);
        
    }//GEN-LAST:event_bt_listarActionPerformed

    private void bt_incidenciaporidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incidenciaporidActionPerformed
      
        Incidencia_por_id l = new Incidencia_por_id(this, true);
        l.setLocationRelativeTo(null);
        l.setVisible(true);

    }//GEN-LAST:event_bt_incidenciaporidActionPerformed

    private void bt_incidencia_por_empeladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incidencia_por_empeladoActionPerformed

        Incidencias_creadas_por_empleado l = new Incidencias_creadas_por_empleado(this, true);
        l.setLocationRelativeTo(null);
        l.setVisible(true);

    }//GEN-LAST:event_bt_incidencia_por_empeladoActionPerformed

    private void bt_incidencias_para_empleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_incidencias_para_empleadoActionPerformed

        Incidencias_destinadass_a_empleado l = new Incidencias_destinadass_a_empleado(this, true);
        l.setLocationRelativeTo(null);
        l.setVisible(true);

    }//GEN-LAST:event_bt_incidencias_para_empleadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_incidencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_incidencias().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_incidencia_por_empelado;
    private javax.swing.JButton bt_incidenciaporid;
    private javax.swing.JButton bt_incidencias_para_empleado;
    private javax.swing.JButton bt_ingresar;
    private javax.swing.JButton bt_listar;
    private javax.swing.JButton jButton2Salir;
    // End of variables declaration//GEN-END:variables
}
