/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz_gráfica;

import POJO.Empleado;
import gestionConsultas.EmpleadoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class Modificar_empleado extends javax.swing.JDialog {

    EmpleadoDAO empleadoDao = new EmpleadoDAO();
    ArrayList<Empleado> lista_empleados = new ArrayList<>();

    Empleado selecionado;

    int id_Selecionado;
    String nombre_Selecionado;
    String user_Selecionado;
    String pass_Selecionado;
    String tel_Selecionado;

    /**
     * Creates new form Insertar_empleado
     */
    public Modificar_empleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        lista_empleados = empleadoDao.listarEmpleados();
        bt_aceptar.setEnabled(false);

        if (!lista_empleados.isEmpty()) {
            for (Empleado em : lista_empleados) {
                cb_empleados.addItem(em); // Guardar objetos en lugar de nombres
            }
        }

        et_user.setEnabled(false);
        et_nombre.setEnabled(false);
        et_pass.setEnabled(false);
        et_tel.setEnabled(false);
        et_nombre.setEditable(false);
        et_user.setEditable(false);
        et_pass.setEditable(false);
        et_tel.setEditable(false);

        cb_empleados.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cb_empleados.getSelectedItem() != null) {

                    et_user.setEnabled(true);
                    et_nombre.setEnabled(true);
                    et_pass.setEnabled(true);
                    et_tel.setEnabled(true);
                    et_nombre.setEditable(true);
                    et_user.setEditable(true);
                    et_pass.setEditable(true);
                    et_tel.setEditable(true);

                    selecionado = (Empleado) cb_empleados.getSelectedItem();

                    lb_id.setText(String.valueOf(selecionado.getId_empleado()));
                    et_nombre.setText(selecionado.getNombre_completo());
                    et_user.setText(selecionado.getNombre_usuario());
                    et_pass.setText(selecionado.getContrasena());
                    et_tel.setText(selecionado.getTelefono_contacto());

                    bt_aceptar.setEnabled(true);


                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        et_nombre = new javax.swing.JTextField();
        et_user = new javax.swing.JTextField();
        et_pass = new javax.swing.JTextField();
        et_tel = new javax.swing.JTextField();
        bt_aceptar = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cb_empleados = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre usuario:");

        jLabel2.setText("Contraseña:");

        jLabel3.setText("Nombre completo:");

        jLabel4.setText("Teléfono de contacto:");

        et_nombre.setToolTipText("");

        bt_aceptar.setText("Aceptar");
        bt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aceptarActionPerformed(evt);
            }
        });

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecciona un empleado:");

        jLabel6.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_salir)
                                .addGap(18, 18, 18)
                                .addComponent(bt_aceptar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(et_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(et_tel, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(et_pass, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                        .addComponent(et_user, javax.swing.GroupLayout.Alignment.LEADING))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_id))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_id))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(et_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(et_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(et_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(et_tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_aceptar)
                    .addComponent(bt_salir))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aceptarActionPerformed

        // Verificar si hay campos vacíos
        if (et_nombre.getText().isEmpty() || et_user.getText().isEmpty()
                || et_pass.getText().isEmpty() || et_tel.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos antes de continuar", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        id_Selecionado = Integer.parseInt(lb_id.getText());
        nombre_Selecionado = et_nombre.getText();
        user_Selecionado = et_user.getText();
        pass_Selecionado = et_pass.getText();
        tel_Selecionado = et_tel.getText();

        // Verificar si los campos no han cambiado
        if (selecionado.getNombre_completo().equalsIgnoreCase(nombre_Selecionado)
                && selecionado.getNombre_usuario().equalsIgnoreCase(user_Selecionado)
                && selecionado.getContrasena().equalsIgnoreCase(pass_Selecionado)
                && selecionado.getTelefono_contacto().equalsIgnoreCase(tel_Selecionado)) {
            JOptionPane.showMessageDialog(this, "Debes cambiar al menos uno de los datos", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        
        Empleado em = new Empleado(id_Selecionado,  user_Selecionado, pass_Selecionado,nombre_Selecionado, tel_Selecionado);
        if (empleadoDao.modificar_empleado(em)) {
            JOptionPane.showMessageDialog(this, "Empleado modificado con éxito", "Empleado modificado", JOptionPane.WARNING_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido modificar el empleado en la base de datos", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            dispose();
        }

    }//GEN-LAST:event_bt_aceptarActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_empleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar_empleado dialog = new Modificar_empleado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aceptar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JComboBox<Empleado> cb_empleados;
    private javax.swing.JTextField et_nombre;
    private javax.swing.JTextField et_pass;
    private javax.swing.JTextField et_tel;
    private javax.swing.JTextField et_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb_id;
    // End of variables declaration//GEN-END:variables
}
