/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package interfaz_gráfica;

import POJO.Empleado;
import gestionConsultas.EmpleadoDAO;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author edulumulu
 */
public class Modificar_contrasena extends javax.swing.JDialog {

    EmpleadoDAO empleadoDao = new EmpleadoDAO();
    ArrayList<Empleado> lista_empleados = new ArrayList<>();

    Empleado selecionado;

    int id_Selecionado;
    String pass_nueva;
    

    /**
     * Creates new form Insertar_empleado
     */
    public Modificar_contrasena(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        //listo empleados y los cargo en el combobox 
        lista_empleados = empleadoDao.listarEmpleados();
        
        if (!lista_empleados.isEmpty()) {
            for (Empleado em : lista_empleados) {
                cb_empleados.addItem(em); // Guardar objetos en lugar de nombres
            }
        }

        //Deshabilito el botón aceptar y los campos que muestran los datos del empleado
        bt_aceptar.setEnabled(false);
        lb_id.setEnabled(false);
        lb_user.setEnabled(false);
        lb_contra_antigua.setEnabled(false);
        et_pass_nueva.setEnabled(false);
        et_pass_nueva.setEditable(false);

        //listener que habilita los datos del empleado selecionado y el campo para modificar la contraseña. Habilita el boton aceptar
        cb_empleados.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (cb_empleados.getSelectedItem() != null) {

                    et_pass_nueva.setEnabled(true);
                    et_pass_nueva.setEditable(true);
                    
                    selecionado = (Empleado) cb_empleados.getSelectedItem();

                    lb_id2.setText(String.valueOf(selecionado.getId_empleado()));
                    lb_user2.setText(selecionado.getNombre_usuario());
                    lb_pass2.setText(selecionado.getContrasena());

                    bt_aceptar.setEnabled(true);


                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        et_pass_nueva = new javax.swing.JTextField();
        bt_aceptar = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cb_empleados = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lb_id = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        lb_contra_antigua = new javax.swing.JLabel();
        lb_id2 = new javax.swing.JLabel();
        lb_user2 = new javax.swing.JLabel();
        lb_pass2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar contraseña");
        setResizable(false);

        jLabel1.setText("Nombre usuario:");

        jLabel2.setText("Contraseña:");

        jLabel4.setText("Nueva contrasena:");

        bt_aceptar.setText("Aceptar");
        bt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aceptarActionPerformed(evt);
            }
        });

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        jLabel5.setText("Selecciona un empleado:");

        jLabel6.setText("Id:");

        lb_id2.setForeground(new java.awt.Color(0, 51, 255));
        lb_id2.setText("id");

        lb_user2.setForeground(new java.awt.Color(0, 51, 255));
        lb_user2.setText("user");

        lb_pass2.setForeground(new java.awt.Color(0, 51, 255));
        lb_pass2.setText("pass");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_user)
                            .addComponent(lb_contra_antigua)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lb_id)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(et_pass_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_user2)
                            .addComponent(lb_pass2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(bt_salir)
                            .addGap(18, 18, 18)
                            .addComponent(bt_aceptar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lb_id2)))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_id)
                .addGap(18, 18, 18)
                .addComponent(lb_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cb_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_contra_antigua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lb_id2))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lb_user2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lb_pass2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(et_pass_nueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_aceptar)
                    .addComponent(bt_salir))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Comprueba qeu el campo no esté vacío y que no coincida con la contraseña antigua
     * @param evt 
     */
    private void bt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aceptarActionPerformed

        // Verificar si hay campos vacíos
        if (et_pass_nueva.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes la nueva contrasena antes de continuar", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        id_Selecionado = Integer.parseInt(lb_id2.getText());
        pass_nueva = et_pass_nueva.getText();
        

        // Verificar si los campos no han cambiado
        if (selecionado.getContrasena().equalsIgnoreCase(pass_nueva)) {
            JOptionPane.showMessageDialog(this, "La contraseña debe ser diferente a la antigua", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Empleado em = new Empleado(id_Selecionado, nombre_Selecionado, user_Selecionado, pass_Selecionado, tel_Selecionado);
        if (empleadoDao.modificar_contrasena_empleado(id_Selecionado, pass_nueva)) {
            JOptionPane.showMessageDialog(this, "contraseña modificada con éxito", "Empleado modificado", JOptionPane.WARNING_MESSAGE);
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "No se ha podido modificar la contraseña en la base de datos", "Acción fallida", JOptionPane.WARNING_MESSAGE);
            dispose();
        }

    }//GEN-LAST:event_bt_aceptarActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_contrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Modificar_contrasena dialog = new Modificar_contrasena(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aceptar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JComboBox<Empleado> cb_empleados;
    private javax.swing.JTextField et_pass_nueva;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lb_contra_antigua;
    private javax.swing.JLabel lb_id;
    private javax.swing.JLabel lb_id2;
    private javax.swing.JLabel lb_pass2;
    private javax.swing.JLabel lb_user;
    private javax.swing.JLabel lb_user2;
    // End of variables declaration//GEN-END:variables
}
